In [ ]:
import numpy as np

In [ ]:
# 1 theke 10 er moddhe value thakbe erom data niye 3x4 matrix banachhi
arr=np.random.randint(1,10 ,(3,4))

In [ ]:
arr

array([[3, 7, 6, 8],
       [1, 8, 9, 3],
       [7, 4, 2, 4]])

In [ ]:
#transpose of array
arr.T

array([[3, 1, 7],
       [7, 8, 4],
       [6, 9, 2],
       [8, 3, 4]])

In [ ]:
#2d data ke 1d convert kore debe
arr.flatten()

array([3, 7, 6, 8, 1, 8, 9, 3, 7, 4, 2, 4])

In [ ]:
#let's take an array
arr1=np.array([1,2,3,3,4])

In [ ]:
arr1.ndim

1

In [ ]:
#dimension ta 1 theke 2 te chole jabe expand_dims() use kore
arr2=np.expand_dims(arr1,axis=1)
arr3=np.expand_dims(arr1,axis=0)

In [ ]:
#axis=0 rakhle dimension change hobe na
print('arr1:')
print(arr1)
print('dimension of arr1:')
print(arr1.ndim)

#axis=1 thakle dimension change hobe
print('arr2:')
print(arr2)
print('dimension of arr2:')
print(arr2.ndim)

arr1:
[1 2 3 3 4]
dimension of arr1:
1
arr2:
[[1]
 [2]
 [3]
 [3]
 [4]]
dimension of arr2:
2


In [ ]:
data=np.array([ [1] , [2] , [3] ])

In [ ]:
data

array([[1],
       [2],
       [3]])

In [ ]:
#list er vetor e list ache , tate ekta data thakle o seta squeeze kore
#ekta list er vetor e diye debe
np.squeeze(data)

array([1, 2, 3])

In [ ]:
arr1

array([1, 2, 3, 3, 4])

In [ ]:
#use of repeat function :
# arr1 ke 3 bar repeat korbe
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [ ]:
#ebar data gulor position shift korabo
print('arr1:',arr1)
#ebar prottek ta element 3 ghor kore shift korabo:
np.roll(arr1 ,3 )

arr1: [1 2 3 3 4]


array([3, 3, 4, 1, 2])

In [ ]:
#ebar data gulo ke ekta 2d matrix er diagonal element e rakhbo:
print('arr1:',arr1)
print("Diagonal form:")
np.diag(arr1)

arr1: [1 2 3 3 4]
Diagonal form:


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [ ]:
#binary operation in numpy:
#genarate two arrays
arr1=np.random.randint(1,10 , (3,4))
arr2=np.random.randint(1,10 , (3,4))

In [ ]:
arr1

array([[8, 8, 1, 5],
       [5, 8, 3, 3],
       [3, 1, 1, 3]])

In [ ]:
arr2

array([[9, 5, 1, 5],
       [2, 4, 8, 7],
       [9, 6, 8, 1]])

In [ ]:
#remainder:
arr1%arr2

array([[8, 3, 0, 0],
       [1, 0, 3, 3],
       [3, 1, 1, 0]])

In [ ]:
#arr1_ij ^ arr2_ij
arr1**arr2

array([[134217728,     32768,         1,      3125],
       [       25,      4096,      6561,      2187],
       [    19683,         1,         1,         3]])

In [ ]:
#and operation:
arr1 & arr2

array([[8, 0, 1, 5],
       [0, 0, 0, 3],
       [1, 0, 0, 1]])

In [ ]:
#or operation:
arr1 | arr2

array([[ 9, 13,  1,  5],
       [ 7, 12, 11,  7],
       [11,  7,  9,  3]])

In [ ]:
#negate operation:
~arr1

array([[-9, -9, -2, -6],
       [-6, -9, -4, -4],
       [-4, -2, -2, -4]])

String function in numpy array

In [ ]:
arr=np.array(['thomas','muller'])

In [ ]:
arr

array(['thomas', 'muller'], dtype='<U6')

In [ ]:
#ebar eta ke upper case niye aso:
np.char.upper(arr)

array(['THOMAS', 'MULLER'], dtype='<U6')

In [ ]:
#convert title to upper case:
#title mane first alphabet ta boro kore debe
np.char.title(arr)

array(['Thomas', 'Muller'], dtype='<U6')

In [ ]:
#capitalize case
# Same as title
np.char.capitalize(arr)

array(['Thomas', 'Muller'], dtype='<U6')

Mathematical function in NUMPY

In [ ]:
arr_test=np.random.randint(0,90,(3,4))

In [ ]:
arr_test

array([[51, 43, 14, 27],
       [38, 32, 44,  3],
       [10,  9, 17, 54]])

In [ ]:
#ebar eder sobar sine value  ber kore dao:
np.sin(arr_test)

array([[ 0.67022918, -0.83177474,  0.99060736,  0.95637593],
       [ 0.29636858,  0.55142668,  0.01770193,  0.14112001],
       [-0.54402111,  0.41211849, -0.96139749, -0.55878905]])

In [ ]:
#cos value
np.cos(arr_test)

array([[ 0.7421542 ,  0.5551133 ,  0.13673722, -0.29213881],
       [ 0.95507364,  0.83422336,  0.99984331, -0.9899925 ],
       [-0.83907153, -0.91113026, -0.27516334, -0.82930983]])

In [ ]:
#tan value:
np.tan(arr_test)

array([[ 0.90308615, -1.49838734,  7.24460662, -3.2737038 ],
       [ 0.31030966,  0.66100604,  0.0177047 , -0.14254654],
       [ 0.64836083, -0.45231566,  3.49391565,  0.6738001 ]])

In [ ]:
#log value:
np.log10(arr_test)

array([[1.70757018, 1.63346846, 1.14612804, 1.43136376],
       [1.5797836 , 1.50514998, 1.64345268, 0.47712125],
       [1.        , 0.95424251, 1.23044892, 1.73239376]])

In [ ]:
#exponent chai:
np.exp(arr_test)

array([[1.40934908e+22, 4.72783947e+18, 1.20260428e+06, 5.32048241e+11],
       [3.18559318e+16, 7.89629602e+13, 1.28516001e+19, 2.00855369e+01],
       [2.20264658e+04, 8.10308393e+03, 2.41549528e+07, 2.83075330e+23]])

In [ ]:
#square root chai:
np.sqrt(arr_test)

array([[7.14142843, 6.55743852, 3.74165739, 5.19615242],
       [6.164414  , 5.65685425, 6.63324958, 1.73205081],
       [3.16227766, 3.        , 4.12310563, 7.34846923]])

In [ ]:
#power function
#here power 2:
np.power(arr_test,2)

array([[2601, 1849,  196,  729],
       [1444, 1024, 1936,    9],
       [ 100,   81,  289, 2916]])

In [ ]:
#mean of the data
np.mean(arr_test)

28.5

In [ ]:
#median of the data:
np.median(arr_test)

29.5

In [ ]:
#let's see the standard deviation:
np.std(arr_test)

16.899211026948368

In [ ]:
#minimum element
np.min(arr_test)

3

In [ ]:
#maximum element:
np.max(arr_test)

54