Sort search and counting function

In [ ]:
import numpy as np

In [ ]:
arr=np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [ ]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [ ]:
#sort in assending order
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [ ]:
#ami ekta arbitary element diye search korbo je kon position e amra data ta insert korte parbo:
#34 ke amra arr er moddhe kon position e rakhte parbo
np.searchsorted(arr,34)

12

In [ ]:
arr1=np.array([0,345,454,0,0,0,0,0])

In [ ]:
#now count non zero datas in the array:
np.count_nonzero(arr1)

2

In [ ]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [ ]:
#amra dekhte chai kothay kon position e more than 6 er data ache
np.where(arr>6)

(array([5, 8]),)

In [ ]:
#see the elements of that position
arr[ np.where(arr>6) ]

array([ 72, 455])

Byte swapping

In [ ]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [ ]:
arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616,   432345564227567616])

Numpy ---> copies and views

In [ ]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [ ]:
a=np.copy(arr)

arr ar a er location alada , deep copy

In [ ]:
#so we are doing b=arr
b=arr.view()

In [ ]:
b

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [ ]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [ ]:
b[0]=67
print('b=',b)
print('arr=',arr)

b= [ 67   3   4   5   6  72   3   3 455   5   6   6]
arr= [ 67   3   4   5   6  72   3   3 455   5   6   6]


Numpy - matrix library

In [ ]:
import numpy.matlib as nm

In [ ]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

Numpy -- Linear Algebra

In [ ]:
arr1=np.array([[1, 2, 3], [4, 5, 6]])         #dimension 3x2
arr2=np.array([[7, 8], [9, 10], [11, 12]])    #dimension 2x3

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
#dot product or matrix multiplication :
np.dot(arr1,arr2)

array([[ 58,  64],
       [139, 154]])

In [ ]:
#another way was
arr1@arr2

array([[ 58,  64],
       [139, 154]])